server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - "argocd.local"

configs:
  params:
    server.insecure: "true"

  cm:
    accounts.admin.enabled: "true"
    admin.enabled: "true"
